import ArtDesign from 'react-native-vector-icons/AntDesign';
import Entypo from 'react-native-vector-icons/Entypo';
import Evil from 'react-native-vector-icons/EvilIcons';
import Feather from 'react-native-vector-icons/Feather';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import Fontisto from 'react-native-vector-icons/Fontisto';
import Foundation from 'react-native-vector-icons/Foundation';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Material from 'react-native-vector-icons/MaterialIcons';
import MaterialCommunity from 'react-native-vector-icons/MaterialCommunityIcons';
import Octicons from 'react-native-vector-icons/Octicons';
import Zocial from 'react-native-vector-icons/Zocial';
import SimpleLineIcons from 'react-native-vector-icons/SimpleLineIcons';

export const ArtDesignIcons = ArtDesign;
export const EntypoIcons = Entypo;
export const EvilIcons = Evil;
export const FeatherIcons = Feather;
export const FontAwesomeIcons = FontAwesome;
export const FontistoIcons = Fontisto;
export const FoundationIcons = Foundation;
export const IonIcons = Ionicons;
export const MaterialIcons = Material;
export const MaterialCommunityIcons = MaterialCommunity;
export const OcticonsIcons = Octicons;
export const ZocialIcons = Zocial;
export const SimpleLineIconsIcons = SimpleLineIcons;
